#!/usr/bin/env bash
#
# Generate a new site env dir (infra/envs/<name>/main.tf + versions.tf) from
# inputs, ready to commit and hand to onboard-site.sh. This is the one piece of
# onboarding that authors Terraform config; bootstrap-backend + onboard-site do
# the AWS side.
#
# Usage:
#   infra/scripts/new-site.sh --name acme --domain acme.com \
#     --deploy-repo acme/site [options]
#
# Options (defaults in brackets):
#   --project <s>                project_name           [= --name]
#   --zone <s>                   hosted_zone_name       [= --domain]
#   --mgmt-repo <o/r>            mgmt_github_repo        [derekadombek/website-deploy]
#   --branch <s>                 github_branch          [main]
#   --region <s>                 AWS region             [us-west-2]
#   --state-bucket <s>           backend bucket         [<name>-tf-state]
#   --lock-table <s>             backend lock table     [<name>-tf-locks]
#   --state-key <s>              backend key            [sites/<name>/terraform.tfstate]
#   --profile <s>                AWS profile for bootstrap (omitted if empty) []
#   --manage-dns <bool>          [true]
#   --create-zone <bool>         create_hosted_zone     [false]
#   --registrar-in-route53 <bool>                       [false]
#   --create-oidc-provider <bool>                       [true]
#   --www <bool>                 manage_www             [true]

set -euo pipefail

NAME="" PROJECT="" DOMAIN="" ZONE="" DEPLOY_REPO=""
MGMT_REPO="derekadombek/website-deploy" BRANCH="main" REGION="us-west-2"
STATE_BUCKET="" LOCK_TABLE="" STATE_KEY="" PROFILE=""
MANAGE_DNS="true" CREATE_ZONE="false" REGISTRAR_R53="false"
CREATE_OIDC="true" WWW="true"

while [ $# -gt 0 ]; do
  case "$1" in
    --name) NAME="$2"; shift 2;;
    --project) PROJECT="$2"; shift 2;;
    --domain) DOMAIN="$2"; shift 2;;
    --zone) ZONE="$2"; shift 2;;
    --deploy-repo) DEPLOY_REPO="$2"; shift 2;;
    --mgmt-repo) MGMT_REPO="$2"; shift 2;;
    --branch) BRANCH="$2"; shift 2;;
    --region) REGION="$2"; shift 2;;
    --state-bucket) STATE_BUCKET="$2"; shift 2;;
    --lock-table) LOCK_TABLE="$2"; shift 2;;
    --state-key) STATE_KEY="$2"; shift 2;;
    --profile) PROFILE="$2"; shift 2;;
    --manage-dns) MANAGE_DNS="$2"; shift 2;;
    --create-zone) CREATE_ZONE="$2"; shift 2;;
    --registrar-in-route53) REGISTRAR_R53="$2"; shift 2;;
    --create-oidc-provider) CREATE_OIDC="$2"; shift 2;;
    --www) WWW="$2"; shift 2;;
    *) echo "unknown option: $1" >&2; exit 1;;
  esac
done

[ -n "${NAME}" ]        || { echo "--name is required" >&2; exit 1; }
[ -n "${DEPLOY_REPO}" ] || { echo "--deploy-repo is required" >&2; exit 1; }
[ -n "${DOMAIN}" ]      || { echo "--domain is required" >&2; exit 1; }

PROJECT="${PROJECT:-$NAME}"
ZONE="${ZONE:-$DOMAIN}"
STATE_BUCKET="${STATE_BUCKET:-${NAME}-tf-state}"
LOCK_TABLE="${LOCK_TABLE:-${NAME}-tf-locks}"
STATE_KEY="${STATE_KEY:-sites/${NAME}/terraform.tfstate}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_DIR="${SCRIPT_DIR}/../envs/${NAME}"
[ -e "${ENV_DIR}" ] && { echo "env already exists: ${ENV_DIR}" >&2; exit 1; }
mkdir -p "${ENV_DIR}"

# Optional provider profile line.
PROFILE_LINE=""
[ -n "${PROFILE}" ] && PROFILE_LINE="  profile = \"${PROFILE}\""

cat > "${ENV_DIR}/versions.tf" <<EOF
terraform {
  required_version = ">= 1.5.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.40"
    }
  }

  backend "s3" {
    bucket         = "${STATE_BUCKET}"
    key            = "${STATE_KEY}"
    region         = "${REGION}"
    dynamodb_table = "${LOCK_TABLE}"
    encrypt        = true
  }
}

provider "aws" {
  region = "${REGION}"
${PROFILE_LINE}

  default_tags {
    tags = {
      Project   = "${PROJECT}"
      ManagedBy = "Terraform"
    }
  }
}

provider "aws" {
  alias  = "us_east_1"
  region = "us-east-1"
${PROFILE_LINE}

  default_tags {
    tags = {
      Project   = "${PROJECT}"
      ManagedBy = "Terraform"
    }
  }
}
EOF

cat > "${ENV_DIR}/main.tf" <<EOF
# ${PROJECT} — generated by infra/scripts/new-site.sh. Review before applying.

module "site" {
  source = "../../modules/aws/static_site_stack"
  providers = {
    aws           = aws
    aws.us_east_1 = aws.us_east_1
  }

  project_name = "${PROJECT}"
  site_domain  = "${DOMAIN}"

  manage_dns       = ${MANAGE_DNS}
  hosted_zone_name = "${ZONE}"

  create_hosted_zone   = ${CREATE_ZONE}
  registrar_in_route53 = ${REGISTRAR_R53}
  manage_www           = ${WWW}

  deploy_github_repo = "${DEPLOY_REPO}"
  mgmt_github_repo   = "${MGMT_REPO}"
  github_branch      = "${BRANCH}"
  mgmt_environment   = "${NAME}"

  create_oidc_provider = ${CREATE_OIDC}

  tf_state_bucket = "${STATE_BUCKET}"
  tf_lock_table   = "${LOCK_TABLE}"
}

output "s3_bucket" { value = module.site.s3_bucket }
output "cloudfront_distribution_id" { value = module.site.cloudfront_distribution_id }
output "cloudfront_domain_name" { value = module.site.cloudfront_domain_name }
output "site_url" { value = module.site.site_url }
output "hosted_zone_name_servers" { value = module.site.hosted_zone_name_servers }
output "deploy_role_arn" { value = module.site.deploy_role_arn }
output "terraform_role_arn" { value = module.site.terraform_role_arn }
EOF

terraform fmt "${ENV_DIR}" >/dev/null 2>&1 || true

echo "created ${ENV_DIR}"
echo "  domain=${DOMAIN} zone=${ZONE} region=${REGION}"
echo "  state=${STATE_BUCKET}/${STATE_KEY} lock=${LOCK_TABLE}"
echo "Next: review + commit, then bootstrap-backend.sh + onboard-site.sh."
