#!/usr/bin/env bash
#
# Turn on a custom domain for an EXISTING site env (infra/envs/<env>). New TF env
# scaffolds a site that serves the CloudFront default URL (manage_dns = false);
# this flips it to a managed domain: sets manage_dns = true + site_domain +
# hosted_zone_name and the DNS-creation flags, in place. Commit the result and
# re-provision via terraform.yml — it's an additive, in-place change (the
# CloudFront distribution gets the alias + cert; content is untouched).
#
# Does NOT re-run new-site.sh (that refuses to overwrite an existing env). Edits
# the keys the generator already wrote, value-agnostically, so it's re-runnable.
#
# Usage:
#   set-site-domain.sh <env> --domain <d> [options]
#
# Options (defaults in brackets):
#   --zone <s>                   hosted_zone_name        [= --domain]
#   --create-zone <bool>         create_hosted_zone      [false]
#   --registrar-in-route53 <bool>                        [false]
#   --www <bool>                 manage_www              [true]

set -euo pipefail

ENV=""; DOMAIN=""; ZONE=""; CREATE_ZONE="false"; REGISTRAR_R53="false"; WWW="true"

[ $# -gt 0 ] || { echo "usage: set-site-domain.sh <env> --domain <d> [options]" >&2; exit 1; }
ENV="$1"; shift
while [ $# -gt 0 ]; do
  case "$1" in
    --domain) DOMAIN="$2"; shift 2;;
    --zone) ZONE="$2"; shift 2;;
    --create-zone) CREATE_ZONE="$2"; shift 2;;
    --registrar-in-route53) REGISTRAR_R53="$2"; shift 2;;
    --www) WWW="$2"; shift 2;;
    *) echo "unknown option: $1" >&2; exit 1;;
  esac
done

[ -n "${DOMAIN}" ] || { echo "--domain is required" >&2; exit 1; }
ZONE="${ZONE:-$DOMAIN}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_DIR="${SCRIPT_DIR}/../envs/${ENV}"
MAIN="${ENV_DIR}/main.tf"
[ -f "${MAIN}" ] || { echo "no such env: ${MAIN}" >&2; exit 1; }

# Guard: the keys we edit must each appear exactly once, or this env wasn't
# generated by new-site.sh and should be edited by hand.
for key in site_domain manage_dns hosted_zone_name create_hosted_zone registrar_in_route53 manage_www; do
  n="$(grep -cE "^[[:space:]]*${key}[[:space:]]*=" "${MAIN}")"
  [ "${n}" = "1" ] || { echo "expected exactly one '${key} =' line in ${MAIN} (found ${n}); edit by hand" >&2; exit 1; }
done

set_kv() { # <key> <replacement-rhs>
  local key="$1" rhs="$2" tmp
  tmp="$(mktemp)"
  sed -E "s|^([[:space:]]*${key}[[:space:]]*=[[:space:]]*).*\$|\1${rhs}|" "${MAIN}" > "${tmp}"
  mv "${tmp}" "${MAIN}"
}

set_kv site_domain          "\"${DOMAIN}\""
set_kv manage_dns           "true"
set_kv hosted_zone_name     "\"${ZONE}\""
set_kv create_hosted_zone   "${CREATE_ZONE}"
set_kv registrar_in_route53 "${REGISTRAR_R53}"
set_kv manage_www           "${WWW}"

terraform fmt "${ENV_DIR}" >/dev/null 2>&1 || true

echo "set domain on ${ENV}:"
echo "  site_domain=${DOMAIN} hosted_zone_name=${ZONE} manage_dns=true"
echo "  create_hosted_zone=${CREATE_ZONE} registrar_in_route53=${REGISTRAR_R53} manage_www=${WWW}"
echo "Next: review + commit, then re-provision via terraform.yml. If the domain's"
echo "Route 53 zone is new + registered elsewhere, delegate the NS before the ACM"
echo "validation can finish (see onboard-site.sh)."
