# boisevalleydetailing — generated by infra/scripts/new-site.sh. Review before applying.

module "site" {
  source = "../../modules/aws/static_site_stack"
  providers = {
    aws           = aws
    aws.us_east_1 = aws.us_east_1
  }

  project_name = "boisevalleydetailing"
  site_domain  = ""

  manage_dns       = false
  hosted_zone_name = ""

  create_hosted_zone   = false
  registrar_in_route53 = false
  manage_www           = true

  # OIDC provider + deploy/Terraform roles are created once per account by the
  # aws-grant-access action (see infra/access); this stack builds only the site.
}

output "s3_bucket" { value = module.site.s3_bucket }
output "cloudfront_distribution_id" { value = module.site.cloudfront_distribution_id }
output "cloudfront_domain_name" { value = module.site.cloudfront_domain_name }
output "site_url" { value = module.site.site_url }
output "hosted_zone_name_servers" { value = module.site.hosted_zone_name_servers }
